#!/usr/bin/env bash

BASE="-dNOPAUSE -dBATCH -sDEVICE=pdfwrite"
COMPATIBILITY_LEVEL="1.4"
QUALITY="/printer"
SILENT=""
OUTPUT="compressed.pdf"
INPUT=""

while [[ $# -gt 1 ]]; do
    case "$1" in

    --screen | -0)
        QUALITY="/screen"
        ;;

    --ebook | -1)
        QUALITY="/eboot"
        ;;

    --print | -2)
        QUALITY="/printer"
        ;;

    --prepress | -3)
        QUALITY="/prepress"
        ;;

    --compatibility | -c)
        shift
        COMPATIBILITY_LEVEL=$1
        ;;

    --silent | -s)
        SILENT="-dQUIET"
        ;;

    --output | -o)
        shift
        OUTPUT=$1
        ;;

    --input | -i)
        shift
        INPUT=$1
        ;;
    esac
    shift
done

gs "$BASE" $SILENT -dCompatibilityLevel="$COMPATIBILITY_LEVEL" -dPDFSETTINGS="$QUALITY" -sOutputFile="$OUTPUT" "$INPUT"
